name: Node.js Package Release

on:
  release:
    types: [created]
  pull_request: 
    branches: [main]

jobs:

  strategy:
      matrix:
        machines: [ubuntu-latest]
        node-version: [20.x]

  build:
    runs-on: ${{ matrix.machines }}

    steps:
      - name: Checkout code and setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests
        run:
          npm i
          npm test

  publish-gpr:
    needs: build
    runs-on: ${{ matrix.machines }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Node.js and publish the package
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies and publish
        run: npm i 
        
      - name: Publish to the npm packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
