name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs: 
  tests:
    runs-on: ${{matrix.machines}}

    strategy:
      matrix:
        machines: [ubuntu-latest]
        node-version : [20.x]
    
    steps: 
      - name: Test with Node.js ${{matrix.node-versions}} in ${{matrix.machines}}
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: npm install
        run : npm ci
      - name: npm test
        run: npm test 