name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  # push:
  #   branches: [ "main" ]

jobs: 
  tests:
    name: Tests

    strategy:
      matrix:
        machines: [ubuntu-latest]
        node-version : [20.x]

    runs-on: ${{matrix.machines}}
    timeout-minutes: 360
    permissions:
      security-events: write

      actions: read
      contents: read
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Node.js v${{matrix.node-versions}} in the ${{matrix.machines}} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run : npm ci

      - name: Run the Unit Test cases
        run: npm test 